cedar/account/urls.py
from django.urls import path, re_path

from . import views
app_name = "account"

urlpatterns = [

    re_path(r'^$',
            views.IndexViews.as_view(),
            name='index',),

    re_path(r'^login$',
            views.LoginView.as_view(),
            name='login',),

    re_path(r'^register/$',
            views.RegisterView.as_view(),
            name='register',),

    re_path(r'^user/active/(?P<token>.*)$',
            views.ActiveView.as_view(), name='useractive')
    # path('user/active/<str:token>',views.ActiveView.as_view(),name='useractive'),
]

cedar/article/urls.py
from django.urls import path, re_path
from . import views


app_name = "article"

urlpatterns = [
    re_path(r'^user/$',
            views.UserBlogView.as_view(),
            name='user'),

    re_path(r'^user/(?P<author>.*)/article/(?P<id>.*)$',
            views.ArticleView.as_view(),
            name='article'),

    re_path(r'^user/mdeditor/$',
            views.MDEditorView.as_view(),
            name='mdeditor'),
]

cedar/cedar/urls.py
from django.conf import settings
from django.conf.urls.static import static
# from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, re_path, include


urlpatterns = [
    re_path(r'', include('account.urls', namespace='account')),
    re_path(r'', include('article.urls', namespace='articles')),
    re_path(r'', include('oauth.urls', namespace='oauth')),
    # re_path(r'test/', include('testapp.urls')),
    # re_path(r'', login_required(include('oauth.urls', namespace='oauth'))),

    re_path(r'mdeditor/', include('mdeditor.urls')),
    path(r'captcha/', include('captcha.urls')),
    # path('admin/', admin.site.urls),
]

if settings.DEBUG:
    ''' 开发时提供静态文件服务,但不适合生产环境，参考：https://docs.djangoproject.com/zh-hans/4.1/howto/static-files/deployment/'''
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cedar/oauth/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import re_path, path
from . import views


app_name = 'oauth'

urlpatterns = [

    re_path(r'^user/(?P<username>.*)$',
            views.testuser),

    re_path('^user/profile$',
            views.UserProfile.as_view(),
            #     login_required(views.UserCenter.as_view()),
            name='profile'),

    re_path(r'^logout/$',
            views.LogoutView.as_view(),
            name='logout',),
]

cedar/templates/base/UserBase.html
{% extends 'base/indexbase.html' %}

{% block main %} 
<div class="container">
    <div class="row justify-content-md-center" style="width: 100%;margin-left: 0px;margin-right: 0px;">
        <div class="col col-lg-2">
            <img src="https://profile.csdnimg.cn/5/8/0/1_qq_41935112" alt="" style="width: 100%;">
        </div>
        <div class="col col-md-8">
            <p> {{ user.username }}的博客 </p>
            <ul style="display: flex;list-style: none;flex-direction: row;padding: 0;margin: 0;">
                <li><a href="{% url 'oauth:profile' %}"><b>{{ user.username }}</b>&nbsp;&nbsp;</a></li>
                <li><a href="{% url 'oauth:profile' %}"><b>ID：{{ user.id }}</b>&nbsp;&nbsp;</a></li>
                <!-- <li><a href=""><b>{{ user.date_joined }}</b>&nbsp;&nbsp;加入时间</a></li> -->
                <li><a href="{% url 'oauth:profile' %}"><b>{{ user.email }}</b>&nbsp;&nbsp;</a></li>
            </ul>
        </div>
        <div class="col col-lg-2">
            <a href="{% url 'oauth:profile' %}">编辑资料</a>
        </div>
    </div>
</div>

<div class="container">
{% block UserProfile %}{% endblock %}
{% block blog %}{% endblock %}
{% block container %}{% endblock %}
</div>

{% endblock%}

cedar/templates/base/indexbase.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-cn">

<head>
  <meta charset="UTF-8">
  <title>{% block title %}首页{% endblock %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'bootstrap-4.6.1-dist/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'nav/css/style.css' %}/">
  {% block style_css %} {% endblock %}
</head>

<body>
  <select name="x" id="">
    <option value="1" name="t">1</option>
    <option value="2" name="t">2</option>
  </select>
  <span>不能相同</span>
  <select name="x" id="">
    <option value="1" name="t">1</option>
    <option value="2" name="t">2</option>
  </select>
  <div class="navbar navbar-default" style="border-bottom: 1px solid #dee2e6;">
    <div class="container">
      <ul class="nav navbar-nav navbar-list" style="flex-direction: row;">
        <li><a class="navbar-brand" href="{% url 'account:index' %}">Blog-up</a></li>
        <!-- <li><input class="hidden" id="toggle-checkbox" type="search" width="100px"></li> -->
        <li><a class="navbar-brand" href="{% url 'account:index' %}">首页</a></li>
        {% if user.is_authenticated %}
        <li><a class="navbar-brand" href="{% url 'article:user' %}">{{ user.username }}</a></li>
        <li><a class="navbar-brand" href="{% url 'oauth:logout' %}">退出</a></li>
        {% else %}
        
        <li><a class="navbar-brand" href="{% url 'account:login' %}">登陆</a></li>
        <li><a class="navbar-brand" href="{% url 'account:register' %}">注册</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
  
  {% block index %}{% endblock %}
  {% block login %}{% endblock %}
  {% block register %}{% endblock %}
  {% block userCenter %}{% endblock %}
  {% block forget %} {% endblock %}
  {% block userbase %} {% endblock %}
  {% block main %}{% endblock %}

  {% block footer %}
  <div class="modal-footer">
    <address class="text-center">
      <p>关于博客园 | 联系我们 | 广告服务 | ©2004-2018博客</p>
      <div href="#">first.last@example.com</div>
    </address>
  </div>
  {% endblock %}

  
</body>

</html>