cedar/account/urls.py
from django.urls import path, re_path

from . import views
app_name = "account"

urlpatterns = [

    re_path(r'^$',
            views.IndexViews.as_view(),
            name='index',),

    re_path(r'^login$',
            views.LoginView.as_view(),
            name='login',),

    re_path(r'^register/$',
            views.RegisterView.as_view(),
            name='register',),

    re_path(r'^user/active/(?P<token>.*)$',
            views.ActiveView.as_view(), name='useractive')
    # path('user/active/<str:token>',views.ActiveView.as_view(),name='useractive'),
]

cedar/article/urls.py
from django.urls import path, re_path
from . import views


app_name = "article"

urlpatterns = [
    re_path(r'^user/$',
            views.UserBlogView.as_view(),
            name='user'),

    re_path(r'^user/(?P<author>.*)/article/(?P<id>.*)$',
            views.ArticleView.as_view(),
            name='article'),

    re_path(r'^user/mdeditor/$',
            views.MDEditorView.as_view(),
            name='mdeditor'),
]

cedar/cedar/urls.py
from django.conf import settings
from django.conf.urls.static import static
# from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, re_path, include


urlpatterns = [
    re_path(r'', include('account.urls', namespace='account')),
    re_path(r'', include('article.urls', namespace='articles')),
    re_path(r'', include('oauth.urls', namespace='oauth')),
    # re_path(r'test/', include('testapp.urls')),
    # re_path(r'', login_required(include('oauth.urls', namespace='oauth'))),

    re_path(r'mdeditor/', include('mdeditor.urls')),
    path(r'captcha/', include('captcha.urls')),
    # path('admin/', admin.site.urls),
]

if settings.DEBUG:
    ''' 开发时提供静态文件服务,但不适合生产环境，参考：https://docs.djangoproject.com/zh-hans/4.1/howto/static-files/deployment/'''
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cedar/article/models.py
from logging import NullHandler
from re import T
from statistics import mode
from urllib import response
from django.utils import timezone
# from datetime import datetime, timedelta, timezone, tzinfo
# from django.contrib.auth import now
from django.db import models
from mdeditor.fields import MDTextField

# Create your models here.

''' 文章表 '''


class Article(models.Model):

    id = models.AutoField('id', primary_key=True)
    title = models.CharField('title', max_length=150, help_text='标题')
    authorid = models.CharField('作者ID', max_length=50)
    author = models.CharField('author', max_length=50, help_text='作者')
    content = MDTextField(verbose_name='content', help_text='文章内容')
    createdate = models.DateTimeField(
        'createdate', default=timezone.now, help_text='创建日期')
    is_original = models.BooleanField(
        'is_original', help_text='是否原创')
    is_private = models.BooleanField(
        'is_private',  help_text='是否公开')
    is_publish = models.BooleanField(
        'is_publish', help_text='是否发布')
    tags = models.JSONField('标签')
    like = models.IntegerField('点赞数', blank=True)
    pageviews = models.IntegerField('阅读量', blank=True)

    def __str__(self) -> str:
        return "ID:%s .标题：%s" % (self.id, self.title)
        # return self.title

    class Meta:
        ordering = ['-id']
        db_table = 'Article'


''' 文章信息表 '''


class ArticleInfo(models.Model):

    article = models.OneToOneField(
        Article, on_delete=models.CASCADE, primary_key=True)
    updatedate = models.DateField(
        'updatedate', default=timezone.now, help_text='更新日期')
    is_daleted = models.BooleanField(
        'is_daleted', default=False, help_text='是否删除')
    is_top = models.BooleanField('is_top', default=False, help_text='是否置顶')

    def __str__(self) -> str:
        # return f"ID:{self.blogid},创建人:{self.createby}."
        return (f"self.article_id：{self.article_id}")

    class Meta:
        ''' 元数据选项'''
        # 对象的默认排序，用于获取对象列表时
        ordering = ['-article_id']
        db_table = 'ArticleInfo'


class Comment(models.Model):
    ''' 评论表 '''
    article = models.ForeignKey(
        'article', on_delete=models.CASCADE)
    commenterid = models.IntegerField('评论者id', blank=True)
    commenter = models.CharField('评论者', blank=True, max_length=16)
    contents = models.CharField('评论内容', blank=True, max_length=100)
    commentdate = models.DateTimeField('评论时间', default=timezone.now,)
    respon = models.JSONField('回复内容', max_length=255, null=True)

    def __str__(self) -> str:
        return self.commenter

    class Meta:
        ordering = ['-article', '-commentdate']
        db_table = 'Comment'

cedar/article/forms.py
from mdeditor.fields import MDTextFormField
from django import forms
from django.forms import ModelForm


# from article.models import ArticleInfo

# ModelForm 将对照 model 创建表单，参考：https://docs.djangoproject.com/zh-hans/4.1/topics/forms/modelforms/#field-types


class MDEditorModleForm(forms.Form):

    title = forms.CharField(label='')
    content = MDTextFormField(label='')
    is_original = forms.ChoiceField(
        choices=[(True, '原创'), (False, '转载')], label='',)
    is_private = forms.ChoiceField(
        choices=[(True, '所有人可见'), (False, '仅自己可见')], label='')
    #


# class InfoModelForm(ModelForm):
#     ''' Article Info '''

#     class Meta:
#         model = ArticleInfo
#         fields = ['is_original', 'is_private',
#                   'is_top', 'is_daleted', 'is_publish']

cedar/article/views.py
import json
from django.core.cache import cache
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse
from django.views.generic import View, ListView
from django.views.generic.edit import FormView
from django.urls import reverse

from typing import Any, Dict, Optional
from cedar.utils import LoginRequiredMixin
from article.forms import MDEditorModleForm
from article.models import Article, ArticleInfo, Comment
from account.models import BlogUser


class UserBlogView(LoginRequiredMixin, ListView):
    ''' 用户博客页面 '''
    template_name: str = 'user/blog.html'
    paginate_by = 5
    model = Article

    # def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
    #     return render(request, self.template_name)

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        content = super().get_context_data(**kwargs)
        return content

    def get_queryset(self):
        return super().get_queryset()


''' 文章页面 '''


class ArticleView(LoginRequiredMixin, View):
    template_name: str = 'user/article.html'

    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        articleid = kwargs.get('id')
        author = kwargs.get('author')

        # 获得 作者 信息
        author_obj = BlogUser.objects.get(username=author)

        # 获得 文章 信息
        article_obj = Article.objects.get(id=articleid)

        # 获得评论信息,没有评论的话则就为空
        try:
            comment_obj = Comment.objects.get(article_id=articleid)
            respons = json.loads(comment_obj.respon)
        except:
            comment_obj = None
            respons = None

        # 增加 阅读量 功能
        article_obj.pageviews += 1

        return render(request, self.template_name, {
            'article': article_obj,
            'author': author_obj,
            'comments': comment_obj,
            'respons': respons
        })


class MDEditorView(LoginRequiredMixin, FormView):
    ''' 编辑页面 '''

    template_name = 'user/mdeditor.html'
    form_class = MDEditorModleForm

    def post(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        ''' 获取数据 '''
        title = request.POST.get('title')
        content = request.POST.get('content')
        original = request.POST.get('is_original')
        private = request.POST.get('is_private')
        username = request.COOKIES.get('username')

        status = request.POST.get('btn-save', True)

        # 判断是草稿还是发布
        if status:
            ''' 发布 '''
            publish = True

        else:
            ''' 草稿 '''
            publish = False
        sessionid = request.COOKIES['sessionid']
        sessiondict = cache.get("django.contrib.sessions.cache"+sessionid)
        userid = sessiondict['_auth_user_id']
        username = BlogUser.objects.get(id=userid).username

        article = Article.objects.create(
            title=title,
            author=username,
            content=content,
            is_original=original,
            is_private=private,
            is_publish=publish
        )
        ArticleInfo.objects.create(
            article_id=article.id)
        return redirect(reverse('article:user'))
        # return redirect(reverse("article:mdeditor"))

    def form_valid(self, form) -> HttpResponse:
        # form.s
        return super().form_valid(form)

cedar/templates/user/article.html
{% extends 'base/indexbase.html' %}

{% block title %} 文章详情 {% endblock %}


{% block main %}
<div class="container">
    <div class="row">
        <div class="col col-lg-3">
            <div class="row">
                <div class="card border-success mb-3" style="max-width: 18rem;">
                    <div class="card-header bg-transparent border-success">{{ author.username }}</div>
                    <div class="card-body text-success">
                        <h5 class="card-title">{{ author.username }}</h5>
                        <p class="card-text">个人简介：</p>
                    </div>
                    <div class="card-footer bg-transparent border-success">标签</div>
                </div>
            </div>
        </div>
        <div class="col col-lg-9">
            <div>
                <title>title||||<p>{{ article.title }}</p>
                </title>
            </div>
            <div>content <p>{{ article.content}}</p>
            </div>
            {% if user.is_authenticated %}
            <div>
                <!-- 评论展示 -->
                {% for comment in comments %}
                <span>{{ comment.commenter }}</span>&nbsp;<span>在{{ comment.commentdate }}评论说:</span>{{ comment.contents }}
                    <br>
                    {% for respon in respons %} 
                        <span>{{ respon.commener }}在{{ respon.date }}回复{{ respon.to }}说{{ respon.content }}</span>
                    {% endfor %}
                {% endfor %}
            </div>
            <div>
            <!-- 写评论 -->
                <form action="" method="post">
                    {% csrf_token %}
                    <div><input name="" id="" cols="30" rows="10"></input></div>
                    <div><button type="submit">写评论</button></div>
                    <div><a href="">点赞</a></div>
                </form>
            </div>
            {% else %}
            <div>
                <span>请<a href="{% url 'account:login'  %}">登录</a>后评论/点赞</span>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

cedar/templates/user/blog.html
{% extends 'base/userbase.html' %}

{% block blog %}
<div class="row">
    <div class="col-6 col-md-3">
        <li><a href="{% url 'article:mdeditor' %}">发布</a></li>
    </div>
    <!-- 博客文章 -->
    <div class="col-md-9">
        <div style="display: flex;list-style: none;flex-direction: row;">
            <li style="margin: 5px 20px;">最近</li>
            <li style="margin: 5px 20px;">文章</li>
            <li style="margin: 5px 20px;">更多</li>
        </div>
        <div style="display: flex;flex-wrap: nowrap;text-align: center;">
            <span style="margin: 5px 20px;">按最后发布时间</span>
            <span style="margin: 5px 20px;">按访问量排序</span>
        </div>
        {% for a in object_list %}
        <div class="article-item" style="margin: 2px 20px;">
            <div>
                <a href="{% url 'articles:article' a.author a.id %}">{{ a.title }}</a>
                {% if a.is_original %}<span>原创</span>
                {% else %}<span>转载</span>
                {% endif %}
            </div>
            <div>摘要：Mysql</div>
            <div style="display: flex;flex-wrap: nowrap;">
                <div style="margin: 0 20px 20px 0;">
                    &nbsp;{{ a.createdate }}&nbsp;·</span>
                </div>
                <div style="margin: 0 20px 20px 0;">841&nbsp;阅读量&nbsp;· </div>
                <div style="margin: 0 20px 20px 0;">0&nbsp;点赞&nbsp;·</div>
                <div style="margin: 0 20px 20px 0;">0&nbsp;评论</div>
            </div>
        </div>
        {% endfor %}

        <div class="pagination">
            <span class="step-links">
                <!-- {% if page_obj.has_previous %} -->
                <a href="?page=1">&laquo; 首页</a>
                <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
                <!-- {% endif %} -->

                <span class="current">
                    {% for number in page_obj.paginator %}
                    <li><span>{{ number.number }}</span></li>
                    {% endfor %}
                    <!-- Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}. -->
                </span>

                <!-- {% if page_obj.has_next %} -->
                <a href="?page={{ page_obj.next_page_number }}">下一页</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">最后一页 &raquo;</a>
                <!-- {% endif %} -->
            </span>
        </div>
    </div>

</div>

{% endblock %}

cedar/templates/user/mdeditor.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-cn">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'bootstrap-4.6.1-dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'nav/css/style.css' %}/">
    <title>写文章</title>
</head>

<body>
    <main class="container">
        <form action="{% url 'article:mdeditor' %}" method="post">
            {% csrf_token %}
            <div class="row">
                <!-- 后退、标题、保存草稿、发布 按钮 -->
                <div class="col col-lg-2">
                    <a href="{% url 'article:user' %}">后退</a>
                </div>
                <div class="col col-lg-6">
                </div>
                <div class="col col-lg-2">
                    <button type="submit" name="btn-save">保存草稿</button>
                </div>
                <div class="col col-lg-2">
                    <button type="submit"  name="btn-publish">发布</button>
                </div>
            </div>
            <div class="row">
                <div class="col col-lg-11">
                    {{ form.media }}
                    {{ form.as_p }}
                </div>
            </div>
        </form>
    </main>
</body>

</html>

cedar/templates/user/profile.html
{% extends 'base/userbase.html' %}


{% block title %} 个人资料-个人资料中心 {% endblock %}



{% block UserProfile %}
<div class="row" style="margin-top: 88px;">
    <div class="col">
        1 of 2
    </div>
    <!-- <div class="col-6">

    </div> -->
    <div class="col-6">
        <ul style="list-style: none;">
            <li style="width: auto;"><label for="" style="width: 20%;text-align: right;">ID:</label>&nbsp;&nbsp;
                <span>{{ user.id }}</span></li>
            <li style="width: auto;"><label for="" style="width: 20%;text-align: right;">用户名:</label>&nbsp;&nbsp;
                    <span>{{ user.username }}</span></li>
            <li style="width: auto;"><label for="" style="width: 20%;text-align: right;">邮箱:</label>&nbsp;&nbsp;
                <span>{{user.email }}</span></li>
            <li style="width: auto;"><label for="" style="width: 20%;text-align: right;">注册时间:</label>&nbsp;&nbsp;
                <span>{{ user.date_joined }}</span>
            </li>
            <li style="width: auto;">&nbsp;&nbsp;
                <label for="" style="width: 20%;text-align: right;">上次登录:</label><span>{{ user.last_login }}</span>
            </li>
        </ul>
    </div>
    <div class="col">
        2 of 2
    </div>
</div>


{% endblock %}